trigger:
  branches:
    include:
      - master
  paths:
    include:
    - registry.yml
    - .azure/registry-pipelines.yml
    - Dockerfile
    - entrypoint.sh
pr:
  drafts: false
  branches:
    include:
      - '*'
  paths:
    include:
    - src/**

pool: 'ecs_spot'

resources:
  repositories:
    - repository: templates
      type: github
      name: tecsomobi/azure_templates
      endpoint: 'Tecsomobi'

extends:
  template: stages2.yml@templates
  parameters:
    build_steps:
    deploy_templates:
      - name: deploy/steps/register.yml
        hasCredentials: true
        parameters:
          imageName: 'pgbouncer'
          config: registry.yml
        
